import Head from 'next/head'
import Hero from '../components/hero'
import Menu from '../components/menu'
import axios from 'axios'
import styles from '../styles/Home.module.css'
import AdminNav from '../components/admin/admin-nav'
import CurrentOrders from '../components/admin/current-orders'
import { useDispatch } from 'react-redux'
import { setAdmin, setOffline} from '../redux/userSlice'
import { useEffect } from 'react'
import dbConnect from '../utils/mongodb'
import sections from '../models/sections'
import products from '../models/products'
import settings from '../models/settings'
import orders from '../models/orders'



export default function Home({ sectionsProp, itemsList, admin, ordersList, settingsList }) {
  const dispatch = useDispatch()
  const secs = JSON.parse(sectionsProp)
  const items = JSON.parse(itemsList)
  const ords = JSON.parse(ordersList)
  const sets = JSON.parse(settingsList)
  const sectionsList = secs.filter((section) => section.title !== "Extra Toppings")
  
  useEffect(()=>{
    dispatch(setAdmin(admin))
    dispatch(setOffline(sets[0].offline))
  }, [dispatch, admin, sets[0]])
  return (
    <div className={styles.container}>
      <Head>
        <title>Burger Box Seaford</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/order-box.webp" />

      </Head>
      {admin ? 
      <>
      <AdminNav />
      <CurrentOrders orders={ords}/>
      </> :
      <>
    <Hero settings={sets[0]}/> 
   <Menu sectionsList={secs} settings={sets[0]} itemsList={items} admin={admin}/>
   </>
   }
    </div> 
  )
}
export const getServerSideProps = async (ctx) => {
  const dev = process.env.MODE === "DEV" ? true : false;
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

   if (myCookie.token === process.env.TOKEN){
    admin = true
   }
   await dbConnect()
   const sectionsRes = await sections.find(); 
   const sects = JSON.stringify(sectionsRes)
  // const sectionsRes = await axios.get(`${dev ? process.env.DEV_URL : process.env.PROD_URL}/api/sections`);
  const itemsRes = await products.find(); 
  const items = JSON.stringify(itemsRes)
  // const itemsRes = await axios.get(`${dev ? process.env.DEV_URL : process.env.PROD_URL}/api/products`);
  const orderRes = await orders.find();
  const ords = JSON.stringify(orderRes)
  // const res = await axios.get(`${dev ? process.env.DEV_URL : process.env.PROD_URL}/api/orders`);
  const settingsRes = await settings.find()
  const setts = JSON.stringify(sectionsRes)
  // const settingsRes = await axios.get(`${dev ? process.env.DEV_URL : process.env.PROD_URL}/api/settings`);
  return {
    props:{
      sectionsProp:sects,
      itemsList: items,
      ordersList: ords,
      settingsList: setts,
      admin
    }
  }
}