import Head from 'next/head'
import Hero from '../components/hero'
import Menu from '../components/menu'
import axios from 'axios'
import styles from '../styles/Home.module.css'
import AdminNav from '../components/admin/admin-nav'
import CurrentOrders from '../components/admin/current-orders'
import { useDispatch } from 'react-redux'
import { setAdmin, setOffline} from '../redux/userSlice'
import { useEffect } from 'react'


export default function Home({ sections, itemsList, admin, orders, settings }) {
  const dispatch = useDispatch()
  useEffect(()=>{
    dispatch(setAdmin(admin))
    dispatch(setOffline(settings[0].offline))
  }, [dispatch, admin, settings])

  const sectionsList = sections.filter((section) => section.title !== "Extra Toppings")

  return (
    <div className={styles.container}>
      <Head>
        <title>Burger Box Seaford</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/order-box.webp" />

      </Head>
      {admin ? 
      <>
      <AdminNav />
      <CurrentOrders orders={orders}/>
      </> :
      <>
    <Hero settings={settings[0]}/> 
   <Menu sectionsList={sectionsList} settings={settings[0]} itemsList={itemsList} admin={admin}/>
   </>
   }
    </div>
  )
}
export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

   if (myCookie.token === process.env.TOKEN){
    admin = true
   }
  const sectionsRes = await axios.get('http://localhost:3000/api/sections');
  const itemsRes = await axios.get('http://localhost:3000/api/products');
  const res = await axios.get('http://localhost:3000/api/orders');
  const settingsRes = await axios.get('http://localhost:3000/api/settings');
  return {
    props:{
      sections:sectionsRes.data,
      itemsList: itemsRes.data,
      orders: res.data,
      settings: settingsRes.data,
      admin
    }
  }
}